const districts = {
  "Andhra Pradesh": [
    "Anantapur",
    "Chittoor",
    "East Godavarari",
    "Kadapa",
    "Krishna",
    "Kurnool",
    "Srikakulam",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
  ],
  Maharashtra: [
    "Ahmednagar",
    "Akola",
    "Amravati",
    "Beed",
    "Mumbai City",
    "Mumbai Suburban",
    "Nasik",
    "Pune",
    "Thane",
    "Yavatmal",
  ],
  "West Bengal": [
    "Alipurduar",
    "Birbhum",
    "Darjeeling",
    "Howrah",
    "Kalimpong",
    "Kolkata",
    "Maldah",
    "Purulia",
    "South 24 Parganas",
    "West Midnapore",
  ],
};

export default districts;
