const DONATION_BY_PHONE_PREFIX = "donations_by_phone";
const DONATION_BY_EMAIL_PREFIX = "donations_by_email";
const DONATION_PREFIX = "donation";
const MODEL_PREFIX = "model";
const DEVICE_PREFIX = "device";
const DEVICE_BY_LOCATION_INDEX = "devices_by_location";
const AVAILABLE_DEVICES_BY_LOCATION_INDEX = "available_devices_by_location";
const DEVICE_BY_MODEL_PREFIX = "devices_by_model";
const AVAILABLE_DEVICE_BY_MODEL_PREFIX = "available_devices_by_model";
const ORDER_PREFIX = "order";
const ORDERS_BY_LOCATION_INDEX = "orders_by_location";
const DELETED_ORDER_PREFIX = "deleted_order";
const WAITLISTED_ORDERS_BY_LOCATION_INDEX = "waitlisted_orders_by_location";
const UNKNOWN_ERROR_RESPONSE = { code: 100, message: "Unknown error" };
const FEASIBLE_DELIVERY_DISTANCE_KM = 100;

module.exports = {
  DONATION_BY_EMAIL_PREFIX,
  DONATION_BY_PHONE_PREFIX,
  DONATION_PREFIX,
  MODEL_PREFIX,
  DEVICE_PREFIX,
  DEVICE_BY_LOCATION_INDEX,
  DEVICE_BY_MODEL_PREFIX,
  UNKNOWN_ERROR_RESPONSE,
  AVAILABLE_DEVICES_BY_LOCATION_INDEX,
  AVAILABLE_DEVICE_BY_MODEL_PREFIX,
  FEASIBLE_DELIVERY_DISTANCE_KM,
  ORDER_PREFIX,
  ORDERS_BY_LOCATION_INDEX,
  WAITLISTED_ORDERS_BY_LOCATION_INDEX,
  DELETED_ORDER_PREFIX,
};
